### ISSUE TITLE
does not work properly for idea 15

### ISSUE THREAD

**Issue by zafarella** [idok/coffee-lint-plugin#6]
gives following

``` java
3:30:13 PM CoffeeLint plugin: 
undefined:3
_ = require("underscore")
^
SyntaxError: Unexpected token _
  at Object.parse (native)
  at readConfigFile (/usr/local/lib/node_modules/coffeelint/lib/commandline.js:118:17)
  at loadConfig (/usr/local/lib/node_modules/coffeelint/lib/commandline.js:126:18)
  at Object. (/usr/local/lib/node_modules/coffeelint/lib/commandline.js:228:14)
  at Object. (/usr/local/lib/node_modules/coffeelint/lib/commandline.js:254:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object. (/usr/local/lib/node_modules/coffeelint/bin/coffeelint:34:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:4... (show balloon)
3:30:13 PM StreamException:  : input contained no data
```

Settings:

```
Node interpreter=/usr/local/bin/node
Path to coffeelint bin = /usr/local/bin/coffeelint
Coffeelint config file = blah/blah/blah/Gruntfile.coffee
```

Coffeelint settings are as following in the `Gruntfile.coffee`

``` yaml
 coffeelint:
      app: ["<%= yeoman.app %>/src/{,**/}*.coffee"]
      options:
        "max_line_length":
          "level": "ignore"
          "value": 120
        "no_trailing_semicolons":
          "level": "error"
        "no_trailing_whitespace":
          "level": "error"
          "allowed_in_comments": false
          "allowed_in_empty_lines": true
        "camel_case_classes":
          "level": "error"
        "coffeescript_error":
          "level": "error"
        "spacing":
          "left": 0
          "right": 1
        "cyclomatic_complexity":
          "level": "ignore"
          "value": 10
```

Intellij 15.0.5

What could be wrong do u think?
